### ISSUE TITLE
use oob swap for messaging display?

### ISSUE THREAD

**Issue by nerdoc** [bblanchon/django-htmx-messages-framework#2]
Thanks for this great solution. I tried it and it works well, thank you. I just had another idea.

Your approach needs "much" custom Js code to  clone the template and fill it with values using Js, which is inflexible due to "rendering" at the client - if that rendering would be done at the server and the html swapped in via HTMX, you would get all the advantages from  Django's template language too in the toast.

This might sound unnecessary, but I have a good use case for that.

Reasons:
1. All the tools like `hx-swap-oob` are included in htmx already
2. Your solution works perfectly when doing a htmx request (that returns a 204 response)., but non-HTMS requests don't show these messages, so at a full page reload the user doesn't see anything.
3. when a HTMX view (e.g. success at UpdateView) redirects (302) to a get request, the event (hence toast) is lost too.
4. You can't "style" the toast without coding that in Js. e.g. I want the toast header be shown  if the message has the extra_tags "dismissible". It's possible with Js, sure, but I think this would be nicer at the server - we have HTMX oob...

I thought about a middleware that somehow "adds" HTML-over-the-wire to the request content with a `hx-swap-oob="beforeend" hx-target="toasts"` kind of thing.

I tried it, but I think I am not smart enough to code that ;-)
What do you think about that approach?

**Comment by bblanchon** [comment]
> Your approach needs "much" custom Js code to clone the template and fill it with values using Js

It's only [34 lines](https://github.com/bblanchon/django-htmx-messages-framework/blob/a63f075dfe87767b74d2dc7162d7048cd5806fc0/htmx_messages/static/toasts.js) and is not application specific: you can reuse it in multiple projects.

> which is inflexible due to "rendering" at the client

To be fair, the client only clones the template provided by the server.

> but non-HTMX requests don't show these messages, so at a full page reload the user doesn't see anything.

That's untrue, [the template](https://github.com/bblanchon/django-htmx-messages-framework/blob/a63f075dfe87767b74d2dc7162d7048cd5806fc0/htmx_messages/templates/toasts.html) includes the classic `{% for message in messages %}` for regular messages.

> when a HTMX view (e.g. success at UpdateView) redirects (302) to a get request, the event (hence toast) is lost too.

I did not notice that in my project, but we can probably solve that with an `if` statement in the [middleware](https://github.com/bblanchon/django-htmx-messages-framework/blob/a63f075dfe87767b74d2dc7162d7048cd5806fc0/htmx_messages/middleware.py). We would have the same issue wit OOB swap.

> I want the toast header be shown if the message has the extra_tags "dismissible"

Can't you do that with a CSS rule?

> I thought about a middleware that somehow "adds" HTML-over-the-wire to the request content with a hx-swap-oob="beforeend" hx-target="toasts" kind of thing.

Appending to the HTML content from the middleware should be possible; I'll try.

**Comment by nerdoc** [comment]
> > Your approach needs "much" custom Js code to clone the template and fill it with values using Js
> 
> It's only [34 lines](https://github.com/bblanchon/django-htmx-messages-framework/blob/a63f075dfe87767b74d2dc7162d7048cd5806fc0/htmx_messages/static/toasts.js) and is not application specific: you can reuse it in multiple projects.
ok, true.


> > which is inflexible due to "rendering" at the client
> 
> To be fair, the client only clones the template provided by the server.

Yes. I tried to fix the "dismissible" issue there, see below. But maybe CSS is a better approach there.

> 
> > but non-HTMX requests don't show these messages, so at a full page reload the user doesn't see anything.
> 
> That's untrue, [the template](https://github.com/bblanchon/django-htmx-messages-framework/blob/a63f075dfe87767b74d2dc7162d7048cd5806fc0/htmx_messages/templates/toasts.html) includes the classic `{% for message in messages %}` for regular messages.

Yes, I didn't see that in the tutorial, but your code includes it, thanks & sorry.
> 
> > when a HTMX view (e.g. success at UpdateView) redirects (302) to a get request, the event (hence toast) is lost too.
> 
> I did not notice that in my project, but we can probably solve that with an `if` statement in the [middleware](https://github.com/bblanchon/django-htmx-messages-framework/blob/a63f075dfe87767b74d2dc7162d7048cd5806fc0/htmx_messages/middleware.py). We would have the same issue wit OOB swap.

ok. True too.

**Comment by nerdoc** [comment]
> > I want the toast header be shown if the message has the extra_tags "dismissible"
> 
> Can't you do that with a CSS rule?

Yes. she "show" part is possible. But I need to remove the "hide after 6 seconds" too then. I have to think about that and use some more Js. But It'll work.
> 
> > I thought about a middleware that somehow "adds" HTML-over-the-wire to the request content with a hx-swap-oob="beforeend" hx-target="toasts" kind of thing.
> 
> Appending to the HTML content from the middleware should be possible; I'll try.

I didn't achieve that yet. It would be much easier to append to an existing toasts container. Turbo-Django does it this way - and I think of adding toasts / messages using websockets with HTMX - here the oob approach would be better IMHO.

**Comment by Bynzski** [comment]
> > > when a HTMX view (e.g. success at UpdateView) redirects (302) to a get request, the event (hence toast) is lost too.
> > 
> > 
> > I did not notice that in my project, but we can probably solve that with an `if` statement in the [middleware](https://github.com/bblanchon/django-htmx-messages-framework/blob/a63f075dfe87767b74d2dc7162d7048cd5806fc0/htmx_messages/middleware.py). We would have the same issue wit OOB swap.
> 

I've been struggling with this all morning, I ended up just hard coding the response.status_code in the middleware to 200 for now, wondering if there is any approach we can take as allauth does a lot of 304's when fiddling with the user/email fields

**Comment by bblanchon** [comment]
@jaystabins, [I added support for redirects in the main branch](https://github.com/bblanchon/django-htmx-messages-framework/commit/532c45298d3e768a8c694bc3de0b0a460fa07364).
If you have more trouble with redirects, please [open a new issue](https://github.com/bblanchon/django-htmx-messages-framework/issues/new/choose) so we can keep this thread focused on OOB swaps.

@nerdoc, [I changed the implementation to use OOB swaps in the "oob" branch](https://github.com/bblanchon/django-htmx-messages-framework/commit/a7c88edfc16c9494dec8f85f91e6094cedb53125). Please let me know what you think.

**Comment by bblanchon** [comment]
I published [a video](https://youtu.be/dc4fhli61bQ) and [an article](https://blog.benoitblanchon.fr/django-htmx-messages-framework-oob/) about the OOB technique.
For now, I plan on keeping the code in the "oob" branch.
