### ISSUE TITLE
toast doesn't appear when redirecting

### ISSUE THREAD

**Issue by oussama-he** [bblanchon/django-htmx-messages-framework#3]
I'm using the oob approach found in `oob` branch and it works correctly with me, except in one case where the toast doesn't appear.

I have a view that looks like the below:
```py
@login_required
def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    # doing some stuff also ... 
 
    messages.success(request, "Category successfully deleted.")
    response = HttpResponse()
    response["HX-Redirect"] = reverse_lazy("core:main")
    return response
```
What's wrong with my view and how can I fix it?
Thank you in advance.

**Comment by bblanchon** [comment]
Hi @oussama-he,

Thank you very much for reporting this issue.
I added an `if` statement to check if the `HX-Redirect` header is present.
Please pull the `oob` branch again and let me know if that fixed your issue.

Best regards,
Benoit

**Comment by oussama-he** [comment]
I've tried the new solution, but it didn't work for me. I tried this #4 and it works now.

**Comment by bblanchon** [comment]
Cool. Thanks!
