### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by HamedAsgariRayan** [bblanchon/django-htmx-messages-framework#8]
Hi

Thank you so much for your creative and valuable package. I have a Django project that works with Bootstrap 4. When I want to use your package, messages are not shown correctly. Could you tell me which sections need to be changed and how?

Thank you again for your cooperation and great package

Best regards

Hamed

**Comment by bblanchon** [comment]
Hi Hamed,

The existing code was written for Bootstrap 5.
If you want to modify it to work with Bootstrap 4, you must modify the following.

https://github.com/bblanchon/django-htmx-messages-framework/blob/165362040ff9b3730dc87bdbfadc9218f63a9f69/htmx_messages/templates/toasts.html#L1-L16

https://github.com/bblanchon/django-htmx-messages-framework/blob/165362040ff9b3730dc87bdbfadc9218f63a9f69/htmx_messages/static/toasts.js#L21-L22

See Bootstrap 4 documentation here:
https://getbootstrap.com/docs/4.6/components/toasts/

Best regards,
Benoit

**Comment by HamedAsgariRayan** [comment]
Hi

Thank you so much for your valuable package and prompt reply.

Best regards

Hamed
